# Generated by Django 4.0.2 on 2023-06-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prompt')),
            ],
        ),
    ]
