# Generated by Django 4.0.2 on 2023-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generatedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
